"""Generate list-view data from the cleaned press freedom table."""
import json

import pandas as pd

from config import ROOT, display_country

CHANGE_PATH = ROOT / "data" / "processed" / "rsf_europe_change_2015_2025.csv"
DATA_DIR = ROOT / "data"
OUTPUT_PATH = ROOT / "data" / "countries_list.json"
JS_OUTPUT_PATH = ROOT / "assets" / "js" / "countries-data.js"


def build_list_data() -> None:
    """Create JSON and JS list-view data from the canonical change table."""
    if not CHANGE_PATH.exists():
        raise FileNotFoundError(f"Change file not found: {CHANGE_PATH}")

    # One canonical table feeds both the visible list and the hero mini-ranking.
    merged = pd.read_csv(CHANGE_PATH).sort_values("change", ascending=False)
    
    # Convert rows into plain dictionaries so the browser can use them without extra parsing.
    countries_list = []
    for idx, row in merged.iterrows():
        countries_list.append(
            {
                "rank": len(countries_list) + 1,
                "country": display_country(row["country"]),
                "iso3": row["iso3"],
                "score_2015": round(row["score_2015"], 2),
                "score_2025": round(row["score_2025"], 2),
                "change": round(row["change"], 2),
            }
        )
    
    # Write JSON for humans/scripts.
    with open(OUTPUT_PATH, "w") as f:
        json.dump(countries_list, f, indent=2)

    # Write a tiny JS file for press-freedom-map.html. Yes, this is intentionally simple.
    JS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JS_OUTPUT_PATH, "w") as f:
        f.write("// Generated by scripts/list_data_builder.py. Edit the CSV pipeline, not this file.\n")
        f.write("const countriesDataInline = ")
        json.dump(countries_list, f, indent=2, ensure_ascii=False)
        f.write(";\n")
    
    print(f"Saved list data to {OUTPUT_PATH}")
    print(f"Saved inline list data to {JS_OUTPUT_PATH}")
    print(f"Total countries: {len(countries_list)}")


if __name__ == "__main__":
    build_list_data()
